spring.application.name=demo
# Don't change the port
server.port = 9001
# for https
server.forward-headers-strategy=framework 

spring.datasourse.url=jdbc:mysql://loclahost:3306/transport_pro?createDatabase
IfNotExist=true
spring.datasourse.usename=root
spring.datasourse.password=Amypo
spring.datasourse.driver-class-name=com.mysql.cj.jdc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jap.properties.hibernate.format_sql=true
spring.jpa.database-paltform=org.hibernate.dialect.MySQL